In [1]:
import numpy as np

# 行列の作成
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(type(a))
print(a.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [2]:
a[0]

array([1, 2, 3])

In [3]:
a[:,0]

array([1, 4])

In [4]:
a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a[:,0:2]

array([[1, 2],
       [4, 5]])

In [7]:
a+1

array([[2, 3, 4],
       [5, 6, 7]])

In [8]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [9]:
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [10]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
np.dot(a,a.T)

array([[14, 32],
       [32, 77]])

In [13]:
np.linalg.inv(np.dot(a,a.T))

array([[ 1.42592593, -0.59259259],
       [-0.59259259,  0.25925926]])

In [15]:
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
np.arange(0,1,0.3)

array([0. , 0.3, 0.6, 0.9])

In [17]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
np.reshape(np.arange(6),(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
np.linspace(0,2,3)

array([0., 1., 2.])

In [21]:
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [22]:
#行列を結合できる。
#縦方向に結合
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [10,11,12]])
np.r_[a, b]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
np.c_[a,b]

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [45]:
c=np.ones((5,1))

c[1][0]=3.14
print(c)

d=c.T
print(d)

print(np.dot(c,d))

print(np.random.rand(10,1))

[[1.  ]
 [3.14]
 [1.  ]
 [1.  ]
 [1.  ]]
[[1.   3.14 1.   1.   1.  ]]
[[1.     3.14   1.     1.     1.    ]
 [3.14   9.8596 3.14   3.14   3.14  ]
 [1.     3.14   1.     1.     1.    ]
 [1.     3.14   1.     1.     1.    ]
 [1.     3.14   1.     1.     1.    ]]
[[0.84907919]
 [0.78754889]
 [0.4362252 ]
 [0.37216166]
 [0.77912184]
 [0.6211984 ]
 [0.59011204]
 [0.36636855]
 [0.14011393]
 [0.20879566]]


In [52]:
e=np.random.normal(10,2,(2,5))
print(e)

print(e[:,1])

print(e[:,2:4])

f=np.random.rand(5,2)
print(np.dot(e,f))

[[10.37527034  8.60024329 12.4476728  11.02276092 10.38379056]
 [13.57672105  6.43331753  7.24224691 12.50228337 10.84770775]]
[8.60024329 6.43331753]
[[12.4476728  11.02276092]
 [ 7.24224691 12.50228337]]
[[34.97501243 31.01018254]
 [34.71989796 32.09654486]]
